version: '3'

services:
  api:
    build:
      context: ./bookworm_api
      args:
        http_proxy: "${http_proxy}"
    ports:
      - 3000:3000

  ui:
    build:
      context: ./bookworm-ui
    ports:
      - 8080:8080

